In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

In [60]:
data = x_train.shape[0]
flatten_x = x_train.view(-1)
flatten_x.shape

torch.Size([15])

In [61]:
flatten_x

tensor([ 73.,  80.,  75.,  93.,  88.,  93.,  89.,  91.,  90.,  96.,  98., 100.,
         73.,  66.,  70.])

In [75]:
model = nn.Linear(15,2)
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1849,  0.2556,  0.2349, -0.0975,  0.1244, -0.2252, -0.1070,  0.0292,
           0.1552, -0.0328,  0.1897, -0.0357, -0.1769,  0.1917,  0.1519],
         [ 0.1528,  0.2228,  0.0263,  0.2283,  0.1727,  0.1778,  0.1730, -0.0736,
          -0.2232,  0.0311,  0.1302,  0.2567,  0.0767,  0.1478,  0.2060]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.1350,  0.0913], requires_grad=True)]

In [76]:
prediction = model(flatten_x)
prediction

tensor([ 61.7183, 143.8196], grad_fn=<AddBackward0>)

In [113]:
input = torch.randn(2,32,32,3)
data = input.shape[0]
input

tensor([[[[ 0.8270, -0.9225, -0.6259],
          [-1.1492,  0.9020, -2.6973],
          [ 0.3584, -0.2506,  1.0519],
          ...,
          [-0.4080,  1.3029,  1.5033],
          [-0.7846,  1.1604, -0.7440],
          [ 0.4381, -0.3900, -1.3335]],

         [[ 0.0636, -0.5575, -1.0513],
          [ 0.1266, -0.0658,  0.9208],
          [ 0.5893, -0.7400,  0.1411],
          ...,
          [-0.9710,  0.4662,  1.1640],
          [ 1.3887,  0.1332, -2.0982],
          [ 0.5184,  2.0252,  0.9995]],

         [[-0.4679,  2.3189,  1.8993],
          [-0.4614,  1.6666,  0.0228],
          [-0.2538,  1.5449, -0.2980],
          ...,
          [-0.9573,  0.0053, -0.7134],
          [-1.5544,  1.1704, -1.2370],
          [-0.7868,  0.3142, -1.1447]],

         ...,

         [[-0.9054,  0.4867,  1.9183],
          [-0.1287, -1.5171, -0.3142],
          [-1.2954, -3.0803,  0.6147],
          ...,
          [ 0.8582, -0.5489, -2.5474],
          [-0.1210,  0.0094, -1.0962],
          [ 1.3497,  0

In [114]:
fla = input.view(data, -1)
fla

tensor([[ 0.8270, -0.9225, -0.6259,  ..., -0.2232, -0.5720,  0.3509],
        [-0.1046,  1.6861,  0.6156,  ...,  0.2154,  1.4815,  0.1161]])

In [115]:
fla.shape

torch.Size([2, 3072])

In [116]:
model2 = nn.Linear(3072,10)
list(model2.parameters())

[Parameter containing:
 tensor([[-0.0052,  0.0174, -0.0051,  ...,  0.0074,  0.0007,  0.0034],
         [-0.0162,  0.0086, -0.0020,  ..., -0.0020,  0.0029,  0.0117],
         [-0.0140,  0.0080, -0.0113,  ...,  0.0118,  0.0102, -0.0086],
         ...,
         [ 0.0053, -0.0029,  0.0002,  ..., -0.0065, -0.0097, -0.0046],
         [-0.0075,  0.0176, -0.0059,  ..., -0.0058,  0.0097,  0.0017],
         [-0.0112,  0.0079, -0.0034,  ...,  0.0133,  0.0174,  0.0090]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0110, -0.0028, -0.0048,  0.0164, -0.0148, -0.0012,  0.0084,  0.0114,
          0.0068, -0.0088], requires_grad=True)]

In [117]:
m = nn.Sequential(
    nn.Linear(3072,10),
    nn.ReLU()
)

In [118]:
output3 = m(fla)
output3

tensor([[0.0000, 0.2101, 1.2009, 0.0000, 0.0000, 0.1097, 0.0000, 0.6524, 0.0000,
         0.0000],
        [0.0672, 0.8429, 0.2733, 0.2312, 0.0000, 0.0181, 0.0000, 0.1009, 0.1451,
         0.2345]], grad_fn=<ReluBackward0>)